module.exports={
    cookieSecret:'zhangshuiyong',
    dbName:'lambdb',
    dbHost:'localhost',
    stockConfigXml:__dirname+"\\"+'stock.xml',
    stockJsonFile:__dirname+"\\public\\files\\"+'stock.json',
    stockDataHost:"hq.sinajs.cn",
    stockDataHostPathPart:"/list="
}